name: initialize

on:
  create:

env:
  PROJECT_NAME: ${{ GITHUB_REPOSITORY#*/ }}

jobs:
  change-docker-compose-env:
    runs-on: ubuntu-latest

    permissions:
      content: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: change .env file
        run: |
          for folder in $(ls)
          do
            echo COMPOSE_PROJECT_NAME=is-os-${{ env.PROJECT_NAME }}
          done
          
      - name: commit & push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}